// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhbWu9gQXmsBa0LrX7XwD5FraIFVCTm6I',
    appId: '1:753544668517:web:a50ba7eaa91b1b17692d8c',
    messagingSenderId: '753544668517',
    projectId: 'flutterappproject-c9b53',
    authDomain: 'flutterappproject-c9b53.firebaseapp.com',
    storageBucket: 'flutterappproject-c9b53.firebasestorage.app',
    measurementId: 'G-N658W8L2X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-EDlMxHb5Y1hsb9De-VzQWsF-4K3Ubg',
    appId: '1:753544668517:android:f311674ec5244486692d8c',
    messagingSenderId: '753544668517',
    projectId: 'flutterappproject-c9b53',
    storageBucket: 'flutterappproject-c9b53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCivnfYb706jqx-BuAg8FqFoLfL1D2Kb7E',
    appId: '1:753544668517:ios:8fe4ac7a485b0adc692d8c',
    messagingSenderId: '753544668517',
    projectId: 'flutterappproject-c9b53',
    storageBucket: 'flutterappproject-c9b53.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCivnfYb706jqx-BuAg8FqFoLfL1D2Kb7E',
    appId: '1:753544668517:ios:8fe4ac7a485b0adc692d8c',
    messagingSenderId: '753544668517',
    projectId: 'flutterappproject-c9b53',
    storageBucket: 'flutterappproject-c9b53.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhbWu9gQXmsBa0LrX7XwD5FraIFVCTm6I',
    appId: '1:753544668517:web:8de4e6b1a5b9930c692d8c',
    messagingSenderId: '753544668517',
    projectId: 'flutterappproject-c9b53',
    authDomain: 'flutterappproject-c9b53.firebaseapp.com',
    storageBucket: 'flutterappproject-c9b53.firebasestorage.app',
    measurementId: 'G-YC7J3LK33F',
  );
}
